const PAGES_CACHE_NAME = 'pages-cache';
const pagesUrlsToCache = [
    '/',
    '/compiled-css-autogenerated.css',
    '/compiled-js-autogenerated.js'
];

self.addEventListener('install', function(event) {
    // Perform install steps
    event.waitUntil(
        caches.open(PAGES_CACHE_NAME)
            .then(function(cache) {
                // console.log('Opened cache');
                return cache.addAll(pagesUrlsToCache);
            })
            .catch(function(err) {
                console.log(err);
            })
    );
});


self.addEventListener('fetch', function(event) {
    event.respondWith(
        caches.match(event.request)
            .then(function(response) {
                    // Cache hit - return response
                    if (response) {
                        return response;
                    }
                    // else if (localStorage.getItem('my-bot.js')) {
                    //     return new Response(localStorage.getItem('my-bot.js'));
                    // }
                    else {
                        return fetch(event.request);
                    }
                }
            )
            .catch(function(err) {
                console.log(err);
            })
    );
});


